services:

  docker-dind:
    image: docker:dind
    restart: always
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERT_DIR: /certs
    ports:
      - 2376:2376
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

  jenkins-blueocean:
    image: myjenkins-blueocean:2.332.3-1
    restart: on-failure
    networks:
    - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client

networks:
  jenkins:

volumes:
  jenkins-data:
  jenkins-docker-certs:
